# Generated by Django 5.2.7 on 2025-10-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='والد',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='category',
            name='نام',
            field=models.CharField(max_length=100, verbose_name='نام دسته'),
        ),
    ]
