# Generated by Django 5.2.7 on 2025-10-29 23:20

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_والد_category_parent_alter_category_نام'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rentals.category', verbose_name='والد'),
        ),
    ]
