# Generated by Django 5.2.7 on 2025-10-30 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rename_توضیحات_category_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام کالا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price_per_day', models.PositiveIntegerField(verbose_name='قیمت اجاره روزانه (تومان)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='عکس کالا')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.category', verbose_name='دسته')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع اجاره')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان اجاره')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('accepted', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.item', verbose_name='کالا')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اجاره\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست اجاره',
                'verbose_name_plural': 'درخواست\u200cهای اجاره',
            },
        ),
    ]
