# Generated by Django 5.2.7 on 2025-10-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_item_options_rental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'کالا', 'verbose_name_plural': 'کالاها'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'درخواست اجاره (مهمان)', 'verbose_name_plural': 'درخواست\u200cهای اجاره (مهمان)'},
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.item', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='message',
            field=models.TextField(blank=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='renter_name',
            field=models.CharField(max_length=100, verbose_name='نام اجاره\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='renter_phone',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
    ]
