# Generated by Django 5.2.7 on 2025-10-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_item_options_alter_rental_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'رکورد اجاره', 'verbose_name_plural': 'رکوردهای اجاره'},
        ),
        migrations.AlterField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(verbose_name='تاریخ پایان اجاره'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع اجاره'),
        ),
    ]
